trigger:
  - master

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: 'dd491421-bf4b-4eac-a7ae-f1771a4620c0'
  imageRepository: 'deeptisinghdockerzerotohero'
  containerRegistry: 'acrpipelinedemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/examples/first-docker-file/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        pool:
          name: Default   # ✅ Use your self-hosted agent pool here
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
